title: Services
'@extends':
    type: default

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        services:
          type: tab
          title: THEME_SKYLIGHT.SERVICES
          fields:
            header.services:
              type: list
              label: THEME_SKYLIGHT.SERVICES
              style: vertical
              fields:
                .icon:
                  type: filepicker
                  folder: '@self'
                  preview_images: true
                  label: THEME_SKYLIGHT.ICON
                  accept:
                    - .png
                    - .jpg
                .title:
                  type: text
                  label: THEME_SKYLIGHT.TITLE
