enabled: true
favicon:
  user/themes/skylight/images/favicon_128x128.png:
    name: favicon_128x128.png
    type: image/png
    size: 6279
    path: user/themes/skylight/images/favicon_128x128.png
logo:
  user/themes/skylight/images/logo_300.png:
    name: logo_300.png
    type: image/png
    size: 9275
    path: user/themes/skylight/images/logo_300.png
left_footer: '&copy; 2024 COPYRIGHT - Skylight Films'
right_footer: '<a href="https://aaronsosa.org" target="_blank" rel="noopener noreferrer">DESIGNED BY Aaron S.</a>'
blog_thumbnail_width: 600
blog_thumbnail_height: 450
default_background_image:
  user/themes/skylight/images/bg.jpg:
    name: bg.jpg
    type: image/jpeg
    size: 225193
    path: user/themes/skylight/images/bg.jpg
