title: 'skylight films'
default_lang: en
author:
  name: Admin
  email: aasoru@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Skylight Films is a Filmmaking, Commercials & Creative photography company based on the Canary Islands'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
